local config = { 
	[1] = { 
		ID = 1,
		mapid = "xtc",
		X = 137,
		Y = 138,
		sShowName = "安全区",
		nColor = 161,
		bOutLine = 1,
		sImgPath = "icon_xdtzy_02.png",
		sMapName = "安全区",
	},
	[2] = { 
		ID = 2,
		mapid = "剑门外门",
		X = 104,
		Y = 85,
		sShowName = "安全区",
		nColor = 161,
		bOutLine = 1,
		sImgPath = "icon_xdtzy_02.png",
		sMapName = "安全区",
	},
	[3] = { 
		ID = 3,
		mapid = "中州城",
		X = 649,
		Y = 183,
		sShowName = "安全区",
		nColor = 161,
		bOutLine = 1,
		sImgPath = "icon_xdtzy_02.png",
		sMapName = "安全区",
	},
	[4] = { 
		ID = 4,
		mapid = "天玄界",
		X = 47,
		Y = 46,
		sShowName = "安全区",
		nColor = 161,
		bOutLine = 1,
		sImgPath = "icon_xdtzy_02.png",
		sMapName = "安全区",
	},
	[5] = { 
		ID = 5,
		mapid = "北境仙域",
		X = 53,
		Y = 43,
		sShowName = "安全区",
		nColor = 161,
		bOutLine = 1,
		sImgPath = "icon_xdtzy_02.png",
		sMapName = "安全区",
	},
	[6] = { 
		ID = 6,
		mapid = "中央仙域",
		X = 137,
		Y = 30,
		sShowName = "安全区",
		nColor = 161,
		bOutLine = 1,
		sImgPath = "icon_xdtzy_02.png",
		sMapName = "安全区",
	},
}
return config
