local cfg = {
    -- 名称：成就系统名称，客户端使用本地同名配置显示
    -- groups: 成就页签分组，服务端只做兜底
    name = "仙途奇缘",
    groups = {"总览","角色","PVE","PVP","其他"},
    -- milestones: 达成数量后的里程碑奖励
    milestones = {
        {count = 10, reward = "称号：成就卷轴Lv.1", extra = "攻击+88、生命魔法+1888、"},
        {count = 25, reward = "仙法卷轴*3", extra = ""},
        {count = 50, reward = "称号：成就卷轴Lv.2", extra = "对怪增伤+10%，打怪爆率+50%"},
        {count = 75, reward = "千年玄铁*888", extra = ""},
        {count = 100, reward = "称号：成就卷轴Lv.3", extra = "攻击加成+10%，防御加成+10%"},
        {count = 125, reward = "仙品仙法卷轴*2", extra = ""},
        {count = 150, reward = "称号：成就卷轴Lv.4", extra = "全属性+10%"},
        {count = 170, reward = "帝星本源*3", extra = ""},
        {count = 185, reward = "称号：大收藏家", extra = "（全属性+50%，对怪增伤+50%，对人攻速+100%，对怪攻速+100%）"},
    },
    -- details: 单项成就列表，包含条件和奖励
    details = {
        {id = 1, group = "角色", name = "江湖萌新", cond = "角色等级达到：80级", reward = "攻击+5", attr_show = {{label = "攻击", mode = "range", min = 0, max = 5}}},
        {id = 2, group = "角色", name = "初入龙门", cond = "角色等级达到：100级", reward = "攻击+15", attr_show = {{label = "攻击", mode = "range", min = 0, max = 15}}},
        {id = 3, group = "角色", name = "声名初显", cond = "角色等级达到：120级", reward = "攻击+25", attr_show = {{label = "攻击", mode = "range", min = 0, max = 25}}},
        {id = 4, group = "角色", name = "一方豪杰", cond = "角色等级达到：130级", reward = "攻击+35", attr_show = {{label = "攻击", mode = "range", min = 0, max = 35}}},
        {id = 5, group = "角色", name = "九天之巅", cond = "角色等级达到：150级", reward = "攻击+50", attr_show = {{label = "攻击", mode = "range", min = 0, max = 50}}},
        {id = 6, group = "角色", name = "转生之人Lv.1", cond = "角色完成1大陆转生", reward = "神力倍功+1%", attr_show = {{label = "神力倍功", value = 100, percent = 1}}},
        {id = 7, group = "角色", name = "转生之人Lv.2", cond = "角色完成2大陆转生", reward = "神力倍功+2%", attr_show = {{label = "神力倍功", value = 200, percent = 1}}},
        {id = 8, group = "角色", name = "转生之人Lv.3", cond = "角色完成3大陆转生", reward = "神力倍功+3%", attr_show = {{label = "神力倍功", value = 300, percent = 1}}},
        {id = 9, group = "角色", name = "转生之人Lv.4", cond = "角色完成4大陆转生", reward = "神力倍功+4%", attr_show = {{label = "神力倍功", value = 400, percent = 1}}},
        {id = 10, group = "角色", name = "转生之人Lv.5", cond = "角色完成5大陆转生", reward = "神力倍功+5%", attr_show = {{label = "神力倍功", value = 500, percent = 1}}},
        {id = 11, group = "角色", name = "转生之人Lv.6", cond = "角色完成6大陆转生", reward = "神力倍功+6%", attr_show = {{label = "神力倍功", value = 600, percent = 1}}},
        {id = 12, group = "角色", name = "天下战神Lv.1", cond = "战斗力达到1W", reward = "攻魔道+10", attr_show = {{label = "攻魔道", value = 10}}},
        {id = 13, group = "角色", name = "天下战神Lv.2", cond = "战斗力达到5W", reward = "攻魔道+20", attr_show = {{label = "攻魔道", value = 20}}},
        {id = 14, group = "角色", name = "天下战神Lv.3", cond = "战斗力达到10W", reward = "攻魔道+30", attr_show = {{label = "攻魔道", value = 30}}},
        {id = 15, group = "角色", name = "天下战神Lv.4", cond = "战斗力达到50W", reward = "攻魔道+50", attr_show = {{label = "攻魔道", value = 50}}},
        {id = 16, group = "角色", name = "天下战神Lv.5", cond = "战斗力达到100W", reward = "攻魔道+100", attr_show = {{label = "攻魔道", value = 100}}},
        {id = 17, group = "角色", name = "天下战神Lv.6", cond = "战斗力达到200W", reward = "攻魔道+150", attr_show = {{label = "攻魔道", value = 150}}},
        {id = 18, group = "角色", name = "天下战神Lv.7", cond = "战斗力达到300W", reward = "攻魔道+200", attr_show = {{label = "攻魔道", value = 200}}},
        {id = 19, group = "角色", name = "天下战神Lv.8", cond = "战斗力达到500W", reward = "攻魔道+300", attr_show = {{label = "攻魔道", value = 300}}},
        {id = 20, group = "角色", name = "天下战神Lv.9", cond = "战斗力达到800W", reward = "攻魔道+400", attr_show = {{label = "攻魔道", value = 400}}},
        {id = 21, group = "角色", name = "天下战神Lv.10", cond = "战斗力达到1000W", reward = "攻魔道+500", attr_show = {{label = "攻魔道", value = 500}}},
        {id = 22, group = "角色", name = "初窥天书", cond = "天书等级达到5级", reward = "魔法伤害减少1%", attr_show = {{label = "魔法伤害减少", value = 100, percent = 1}}},
        {id = 23, group = "角色", name = "半卷乾坤", cond = "天书等级达到25级", reward = "魔法伤害减少2%", attr_show = {{label = "魔法伤害减少", value = 200, percent = 1}}},
        {id = 24, group = "角色", name = "无上天书", cond = "天书等级达到50级", reward = "魔法伤害减少3%", attr_show = {{label = "魔法伤害减少", value = 300, percent = 1}}},
        {id = 25, group = "角色", name = "收藏家Lv.1", cond = "累计收集5个不同的装扮", reward = "魔法伤害增加1%", attr_show = {{label = "魔法伤害增加", value = 100, percent = 1}}},
        {id = 26, group = "角色", name = "收藏家Lv.2", cond = "累计收集10个不同的装扮", reward = "魔法伤害增加2%", attr_show = {{label = "魔法伤害增加", value = 200, percent = 1}}},
        {id = 27, group = "角色", name = "收藏家Lv.3", cond = "累计收集20个不同的装扮", reward = "魔法伤害增加3%", attr_show = {{label = "魔法伤害增加", value = 300, percent = 1}}},
        {id = 28, group = "角色", name = "灵根Lv.1", cond = "激活1个灵根", reward = "固定攻击+10", attr_show = {{label = "攻击", mode = "range", min = 0, max = 10}}},
        {id = 29, group = "角色", name = "灵根Lv.2", cond = "激活3个灵根", reward = "固定攻击+20", attr_show = {{label = "攻击", mode = "range", min = 0, max = 20}}},
        {id = 30, group = "角色", name = "灵根Lv.3", cond = "激活5个灵根", reward = "固定攻击+30", attr_show = {{label = "攻击", mode = "range", min = 0, max = 30}}},
        {id = 31, group = "角色", name = "灵根Lv.4", cond = "激活7个灵根", reward = "固定攻击+40", attr_show = {{label = "攻击", mode = "range", min = 0, max = 40}}},
        {id = 32, group = "角色", name = "灵根Lv.5", cond = "激活10个灵根", reward = "固定攻击+50", attr_show = {{label = "攻击", mode = "range", min = 0, max = 50}}},
        {id = 33, group = "角色", name = "五行之力Lv.1", cond = "激活金木水火土灵根", reward = "人物攻击+1%", attr_show = {{label = "人物攻击", value = 100, percent = 1}}},
        {id = 34, group = "角色", name = "五行之力Lv.2", cond = "激活雷风冰焚岩灵根", reward = "人物攻击+2%", attr_show = {{label = "人物攻击", value = 200, percent = 1}}},
        {id = 35, group = "角色", name = "金之力", cond = "X灵根等级达到10级", reward = "神圣一击概率+1%", attr_show = {{label = "神圣一击概率", value = 100, percent = 1}}},
        {id = 36, group = "角色", name = "木之力", cond = "X灵根等级达到10级", reward = "神圣一击概率+1%", attr_show = {{label = "神圣一击概率", value = 100, percent = 1}}},
        {id = 37, group = "角色", name = "水之力", cond = "X灵根等级达到10级", reward = "神圣一击概率+1%", attr_show = {{label = "神圣一击概率", value = 100, percent = 1}}},
        {id = 38, group = "角色", name = "火之力", cond = "X灵根等级达到10级", reward = "神圣一击概率+1%", attr_show = {{label = "神圣一击概率", value = 100, percent = 1}}},
        {id = 39, group = "角色", name = "土之力", cond = "X灵根等级达到10级", reward = "神圣一击概率+1%", attr_show = {{label = "神圣一击概率", value = 100, percent = 1}}},
        {id = 40, group = "角色", name = "雷之力", cond = "X灵根等级达到10级", reward = "神圣一击概率+1%", attr_show = {{label = "神圣一击概率", value = 100, percent = 1}}},
        {id = 41, group = "角色", name = "风之力", cond = "X灵根等级达到10级", reward = "神圣一击概率+1%", attr_show = {{label = "神圣一击概率", value = 100, percent = 1}}},
        {id = 42, group = "角色", name = "冰之力", cond = "X灵根等级达到10级", reward = "神圣一击概率+1%", attr_show = {{label = "神圣一击概率", value = 100, percent = 1}}},
        {id = 43, group = "角色", name = "焚之力", cond = "X灵根等级达到10级", reward = "神圣一击概率+1%", attr_show = {{label = "神圣一击概率", value = 100, percent = 1}}},
        {id = 44, group = "角色", name = "岩之力", cond = "X灵根等级达到10级", reward = "神圣一击概率+1%", attr_show = {{label = "神圣一击概率", value = 100, percent = 1}}},
        {id = 45, group = "角色", name = "修仙之路", cond = "第一次提升境界", reward = "修为+100", attr_show = {{label = "修为", value = 100, color = "#68ecff"}}},
        {id = 46, group = "角色", name = "筑基境", cond = "境界达到X境", reward = "暴击伤害+1%", attr_show = {{label = "暴击伤害", value = 100, percent = 1}}},
        {id = 47, group = "角色", name = "金丹境", cond = "境界达到X境", reward = "暴击伤害+2%", attr_show = {{label = "暴击伤害", value = 200, percent = 1}}},
        {id = 48, group = "角色", name = "元婴境", cond = "境界达到X境", reward = "暴击伤害+3%", attr_show = {{label = "暴击伤害", value = 300, percent = 1}}},
        {id = 49, group = "角色", name = "大乘境", cond = "境界达到X境", reward = "暴击伤害+4%", attr_show = {{label = "暴击伤害", value = 400, percent = 1}}},
        {id = 50, group = "角色", name = "渡劫境", cond = "境界达到X境", reward = "暴击伤害+5%", attr_show = {{label = "暴击伤害", value = 500, percent = 1}}},
        {id = 51, group = "角色", name = "仙人境", cond = "境界达到X境", reward = "暴击伤害+6%", attr_show = {{label = "暴击伤害", value = 600, percent = 1}}},
        {id = 52, group = "角色", name = "称号收集Lv.1", cond = "累计获得5个称号", reward = "固定生命、固定魔法+100", attr_show = {{label = "生命值", value = 100}, {label = "固定魔法", value = 100}}},
        {id = 53, group = "角色", name = "称号收集Lv.2", cond = "累计获得10个称号", reward = "固定生命、固定魔法+300", attr_show = {{label = "生命值", value = 300}, {label = "固定魔法", value = 300}}},
        {id = 54, group = "角色", name = "称号收集Lv.3", cond = "累计获得30个称号", reward = "固定生命、固定魔法+500", attr_show = {{label = "生命值", value = 500}, {label = "固定魔法", value = 500}}},
        {id = 55, group = "角色", name = "称号收集Lv.4", cond = "累计获得50个称号", reward = "固定生命、固定魔法+800", attr_show = {{label = "生命值", value = 800}, {label = "固定魔法", value = 800}}},
        {id = 56, group = "角色", name = "称号收集Lv.5", cond = "累计获得100个称号", reward = "固定生命、固定魔法+1000", attr_show = {{label = "生命值", value = 1000}, {label = "固定魔法", value = 1000}}},
        {id = 57, group = "角色", name = "背包神器Lv.1", cond = "累计获得1个背包神器", reward = "打怪增伤+1%", attr_show = {{label = "对怪增伤", value = 100, percent = 1}}},
        {id = 58, group = "角色", name = "背包神器Lv.2", cond = "累计获得5个背包神器", reward = "打怪增伤+2%", attr_show = {{label = "对怪增伤", value = 200, percent = 1}}},
        {id = 59, group = "角色", name = "背包神器Lv.3", cond = "累计获得10个背包神器", reward = "打怪增伤+3%", attr_show = {{label = "对怪增伤", value = 300, percent = 1}}},
        {id = 60, group = "角色", name = "光头强Lv.1", cond = "累计砍树10次", reward = "暴击几率+1%", attr_show = {{label = "暴击几率", value = 100, percent = 1}}},
        {id = 61, group = "角色", name = "光头强Lv.2", cond = "累计砍树100次", reward = "暴击几率+1%", attr_show = {{label = "暴击几率", value = 100, percent = 1}}},
        {id = 62, group = "角色", name = "光头强Lv.3", cond = "累计砍树1000次", reward = "暴击几率+1%", attr_show = {{label = "暴击几率", value = 100, percent = 1}}},
        {id = 63, group = "角色", name = "光头强Lv.4", cond = "累计砍树10000次", reward = "暴击几率+1%", attr_show = {{label = "暴击几率", value = 100, percent = 1}}},
        {id = 64, group = "角色", name = "光头强Lv.5", cond = "累计砍树100000次", reward = "暴击几率+1%", attr_show = {{label = "暴击几率", value = 100, percent = 1}}},
        {id = 65, group = "PVE", name = "盟重除妖Lv.1", cond = "击杀一大陆怪物10只", reward = "打怪切割+100", attr_show = {{label = "对怪切割", value = 100}}},
        {id = 66, group = "PVE", name = "盟重除妖Lv.2", cond = "击杀一大陆怪物20只", reward = "打怪切割+100", attr_show = {{label = "对怪切割", value = 100}}},
        {id = 67, group = "PVE", name = "盟重除妖Lv.3", cond = "击杀一大陆怪物50只", reward = "打怪切割+100", attr_show = {{label = "对怪切割", value = 100}}},
        {id = 68, group = "PVE", name = "极光除妖Lv.1", cond = "击杀二大陆怪物50只", reward = "攻击+10", attr_show = {{label = "攻击", mode = "range", min = 0, max = 10}}},
        {id = 69, group = "PVE", name = "极光除妖Lv.2", cond = "击杀二大陆怪物100只", reward = "生命值+100", attr_show = {{label = "生命值", value = 100}}},
        {id = 70, group = "PVE", name = "极光除妖Lv.3", cond = "击杀二大陆怪物500只", reward = "打怪切割+1000", attr_show = {{label = "对怪切割", value = 1000}}},
        {id = 71, group = "PVE", name = "极光除妖Lv.4", cond = "击杀二大陆怪物1000只", reward = "二大陆专属装备宝箱", attr_show = {}},
        {id = 72, group = "PVE", name = "苍云除妖Lv.1", cond = "击杀三大陆怪物100只", reward = "攻击+20", attr_show = {{label = "攻击", mode = "range", min = 0, max = 20}}},
        {id = 73, group = "PVE", name = "苍云除妖Lv.2", cond = "击杀三大陆怪物500只", reward = "生命值+200", attr_show = {{label = "生命值", value = 200}}},
        {id = 74, group = "PVE", name = "苍云除妖Lv.3", cond = "击杀三大陆怪物1000只", reward = "打怪切割+2000", attr_show = {{label = "对怪切割", value = 2000}}},
        {id = 75, group = "PVE", name = "苍云除妖Lv.4", cond = "击杀三大陆怪物3000只", reward = "仙法卷轴*1", attr_show = {}},
        {id = 76, group = "PVE", name = "苍云除妖Lv.5", cond = "击杀三大陆怪物5000只", reward = "三大陆专属装备宝箱", attr_show = {}},
        {id = 77, group = "PVE", name = "若水除妖Lv.1", cond = "击杀四大陆怪物100只", reward = "攻击+30", attr_show = {{label = "攻击", mode = "range", min = 0, max = 30}}},
        {id = 78, group = "PVE", name = "若水除妖Lv.2", cond = "击杀四大陆怪物500只", reward = "生命值+300", attr_show = {{label = "生命值", value = 300}}},
        {id = 79, group = "PVE", name = "若水除妖Lv.3", cond = "击杀四大陆怪物1000只", reward = "打怪切割+3000", attr_show = {{label = "对怪切割", value = 3000}}},
        {id = 80, group = "PVE", name = "若水除妖Lv.4", cond = "击杀四大陆怪物3000只", reward = "仙法卷轴*2", attr_show = {}},
        {id = 81, group = "PVE", name = "若水除妖Lv.5", cond = "击杀四大陆怪物5000只", reward = "四大陆专属装备宝箱", attr_show = {}},
        {id = 82, group = "PVE", name = "红尘除妖Lv.1", cond = "击杀五大陆怪物100只", reward = "攻击+40", attr_show = {{label = "攻击", mode = "range", min = 0, max = 40}}},
        {id = 83, group = "PVE", name = "红尘除妖Lv.2", cond = "击杀五大陆怪物500只", reward = "生命值+400", attr_show = {{label = "生命值", value = 400}}},
        {id = 84, group = "PVE", name = "红尘除妖Lv.3", cond = "击杀五大陆怪物1000只", reward = "打怪切割+4000", attr_show = {{label = "对怪切割", value = 4000}}},
        {id = 85, group = "PVE", name = "红尘除妖Lv.4", cond = "击杀五大陆怪物3000只", reward = "仙法卷轴*3", attr_show = {}},
        {id = 86, group = "PVE", name = "红尘除妖Lv.5", cond = "击杀五大陆怪物5000只", reward = "五大陆专属装备宝箱", attr_show = {}},
        {id = 87, group = "PVE", name = "灵虚除妖Lv.1", cond = "击杀六大陆怪物100只", reward = "攻击+50", attr_show = {{label = "攻击", mode = "range", min = 0, max = 50}}},
        {id = 88, group = "PVE", name = "灵虚除妖Lv.2", cond = "击杀六大陆怪物500只", reward = "生命值+500", attr_show = {{label = "生命值", value = 500}}},
        {id = 89, group = "PVE", name = "灵虚除妖Lv.3", cond = "击杀六大陆怪物1000只", reward = "打怪切割+5000", attr_show = {{label = "对怪切割", value = 5000}}},
        {id = 90, group = "PVE", name = "灵虚除妖Lv.4", cond = "击杀六大陆怪物3000只", reward = "仙法卷轴*5", attr_show = {}},
        {id = 91, group = "PVE", name = "灵虚除妖Lv.5", cond = "击杀六大陆怪物5000只", reward = "六大陆专属装备宝箱", attr_show = {}},
        {id = 92, group = "PVE", name = "极光秘境Lv.1", cond = "击杀极光秘境中怪物50只", reward = "攻击+10", attr_show = {{label = "攻击", mode = "range", min = 0, max = 10}}},
        {id = 93, group = "PVE", name = "极光秘境Lv.2", cond = "击杀极光秘境中怪物100只", reward = "生命值+100", attr_show = {{label = "生命值", value = 100}}},
        {id = 94, group = "PVE", name = "极光秘境Lv.3", cond = "击杀极光秘境中怪物500只", reward = "打怪切割+500", attr_show = {{label = "对怪切割", value = 500}}},
        {id = 95, group = "PVE", name = "苍云秘境Lv.1", cond = "击杀XX秘境中怪物50只", reward = "攻击+20", attr_show = {{label = "攻击", mode = "range", min = 0, max = 20}}},
        {id = 96, group = "PVE", name = "苍云秘境Lv.2", cond = "击杀XX秘境中怪物100只", reward = "生命值+200", attr_show = {{label = "生命值", value = 200}}},
        {id = 97, group = "PVE", name = "苍云秘境Lv.3", cond = "击杀XX秘境中怪物500只", reward = "打怪切割+1000", attr_show = {{label = "对怪切割", value = 1000}}},
        {id = 98, group = "PVE", name = "若水秘境Lv.1", cond = "击杀XX秘境中怪物50只", reward = "攻击+30", attr_show = {{label = "攻击", mode = "range", min = 0, max = 30}}},
        {id = 99, group = "PVE", name = "若水秘境Lv.2", cond = "击杀XX秘境中怪物100只", reward = "生命值+300", attr_show = {{label = "生命值", value = 300}}},
        {id = 100, group = "PVE", name = "若水秘境Lv.3", cond = "击杀XX秘境中怪物500只", reward = "打怪切割+3000", attr_show = {{label = "对怪切割", value = 3000}}},
        {id = 101, group = "PVE", name = "红尘秘境Lv.1", cond = "击杀XX秘境中怪物50只", reward = "攻击+40", attr_show = {{label = "攻击", mode = "range", min = 0, max = 40}}},
        {id = 102, group = "PVE", name = "红尘秘境Lv.2", cond = "击杀XX秘境中怪物100只", reward = "生命值+400", attr_show = {{label = "生命值", value = 400}}},
        {id = 103, group = "PVE", name = "红尘秘境Lv.3", cond = "击杀XX秘境中怪物500只", reward = "打怪切割+4000", attr_show = {{label = "对怪切割", value = 4000}}},
        {id = 104, group = "PVE", name = "灵虚秘境Lv.1", cond = "击杀XX秘境中怪物50只", reward = "攻击+50", attr_show = {{label = "攻击", mode = "range", min = 0, max = 50}}},
        {id = 105, group = "PVE", name = "灵虚秘境Lv.2", cond = "击杀XX秘境中怪物100只", reward = "生命值+500", attr_show = {{label = "生命值", value = 500}}},
        {id = 106, group = "PVE", name = "灵虚秘境Lv.3", cond = "击杀XX秘境中怪物500只", reward = "打怪切割+5000", attr_show = {{label = "对怪切割", value = 5000}}},
        {id = 107, group = "PVE", name = "跨服除妖Lv.1", cond = "击杀跨服怪物10只", reward = "对跨服怪物额外增伤+1%", attr_show = {{label = "跨服怪物额外增伤", value = 100, percent = 1, color = "#68ecff"}}},
        {id = 108, group = "PVE", name = "跨服除妖Lv.2", cond = "击杀跨服怪物100只", reward = "对跨服怪物额外增伤+2%", attr_show = {{label = "跨服怪物额外增伤", value = 200, percent = 1, color = "#68ecff"}}},
        {id = 109, group = "PVE", name = "跨服除妖Lv.3", cond = "击杀跨服怪物500只", reward = "对跨服怪物额外增伤+3%", attr_show = {{label = "跨服怪物额外增伤", value = 300, percent = 1, color = "#68ecff"}}},
        {id = 110, group = "其他", name = "嘴炮宗师", cond = "在世界频道连续发言50次", reward = "人缘+999", attr_show = {{label = "人缘", value = 999, color = "#68ecff"}}},
        {id = 111, group = "其他", name = "卧槽这也能死？", cond = "在安全区死亡", reward = "防御加成+1%", attr_show = {{label = "防御加成", value = 100, percent = 1}}},
        {id = 112, group = "其他", name = "江湖有你", cond = "第一次加入行会", reward = "打怪爆率+1%", attr_show = {{label = "打怪爆率", value = 100, percent = 1}}},
        {id = 113, group = "其他", name = "玄学入门", cond = "强化失败1次", reward = "打怪爆率+5%", attr_show = {{label = "打怪爆率", value = 500, percent = 1}}},
        {id = 114, group = "其他", name = "我不信邪！", cond = "连续强化失败5次", reward = "之后任何强化有1%几率不消耗道具", attr_show = {{label = "强化不消耗道具几率", value = 100, percent = 1, color = "#68ecff"}}},
        {id = 115, group = "其他", name = "系统针对我", cond = "连续强化失败10次", reward = "之后任何强化有3%几率不消耗道具", attr_show = {{label = "强化不消耗道具几率", value = 300, percent = 1, color = "#68ecff"}}},
        {id = 116, group = "其他", name = "我只是路过的！", cond = "被怪物打死时，自己没有造成任何伤害", reward = "对怪增伤+1%", attr_show = {{label = "对怪增伤", value = 100, percent = 1}}},
        {id = 117, group = "其他", name = "不再是一个人", cond = "拥有1个好友", reward = "对怪固定吸血+20", attr_show = {{label = "对怪固定吸血", value = 20}}},
        {id = 118, group = "其他", name = "三五知己", cond = "拥有5个好友", reward = "对怪固定吸血+50", attr_show = {{label = "对怪固定吸血", value = 50}}},
        {id = 119, group = "其他", name = "万人迷", cond = "拥有50个好友", reward = "对怪固定吸血+100", attr_show = {{label = "对怪固定吸血", value = 100}}},
        {id = 120, group = "其他", name = "初窥天书", cond = "天书等级达到5级", reward = "对怪切割+100", attr_show = {{label = "对怪切割", value = 100}}},
        {id = 121, group = "其他", name = "半卷乾坤", cond = "天书等级达到25级", reward = "对怪切割+300", attr_show = {{label = "对怪切割", value = 300}}},
        {id = 122, group = "其他", name = "无上天书", cond = "天书等级达到50级", reward = "对怪切割+500", attr_show = {{label = "对怪切割", value = 500}}},
        {id = 123, group = "其他", name = "沙巴克是我的！", cond = "第一次攻沙胜利时", reward = "攻击伤害+1%", attr_show = {{label = "攻击伤害", value = 100, percent = 1}}},
        {id = 124, group = "其他", name = "花点小钱", cond = "累计充值10元", reward = "对怪切割+100", attr_show = {{label = "对怪切割", value = 100}}},
        {id = 125, group = "其他", name = "家有良田", cond = "累计充值100元", reward = "对怪切割+500", attr_show = {{label = "对怪切割", value = 500}}},
        {id = 126, group = "其他", name = "富甲一方", cond = "累计充值500元", reward = "对怪切割+5000", attr_show = {{label = "对怪切割", value = 5000}}},
        {id = 127, group = "其他", name = "富可敌国", cond = "累计充值1000元", reward = "对怪切割+5w", attr_show = {{label = "对怪切割", value = 50000}}},
        {id = 128, group = "其他", name = "天下神壕", cond = "累计充值3000元", reward = "对怪切割+10W", attr_show = {{label = "对怪切割", value = 100000}}},
        {id = 129, group = "其他", name = "老字就是有钱", cond = "累计充值1W", reward = "对怪切割+20W", attr_show = {{label = "对怪切割", value = 200000}}},
        {id = 130, group = "其他", name = "随便洒洒水", cond = "累计充值2W", reward = "对怪切割+50W", attr_show = {{label = "对怪切割", value = 500000}}},
        {id = 131, group = "其他", name = "此号价值一套房", cond = "累计充值3W", reward = "对怪切割+100W", attr_show = {{label = "对怪切割", value = 1000000}}},
        {id = 132, group = "其他", name = "江湖有你", cond = "第一次加入行会", reward = "怪物格挡+10", attr_show = {{label = "怪物格挡", value = 10}}},
        {id = 133, group = "其他", name = "西游之路", cond = "完成剧情[重走西游]", reward = "攻击+10", attr_show = {{label = "攻击", mode = "range", min = 0, max = 10}}},
        {id = 134, group = "其他", name = "生肖守护", cond = "完成剧情[生肖守护]", reward = "攻击+20", attr_show = {{label = "攻击", mode = "range", min = 0, max = 20}}},
        {id = 135, group = "其他", name = "修复传说", cond = "完成剧情[传说修复局]", reward = "攻击+30", attr_show = {{label = "攻击", mode = "range", min = 0, max = 30}}},
        {id = 136, group = "其他", name = "好看不？", cond = "仙府仙华值达到：1000", reward = "魅力+999", attr_show = {{label = "魅力", value = 999, color = "#68ecff"}}},
        {id = 137, group = "其他", name = "炼丹大师", cond = "炼制全部丹药各1次", reward = "金币回收+1%", attr_show = {{label = "金币回收", value = 100, percent = 1}}},
        {id = 138, group = "其他", name = "御兽师Lv.1", cond = "灵兽全部1星", reward = "对怪增伤+1%", attr_show = {{label = "对怪增伤", value = 100, percent = 1}}},
        {id = 139, group = "其他", name = "御兽师Lv.2", cond = "灵兽全部2星", reward = "对怪增伤+2%", attr_show = {{label = "对怪增伤", value = 200, percent = 1}}},
        {id = 140, group = "其他", name = "御兽师Lv.3", cond = "灵兽全部3星", reward = "对怪增伤+3%", attr_show = {{label = "对怪增伤", value = 300, percent = 1}}},
        {id = 141, group = "其他", name = "寻宝大师", cond = "藏宝图寻宝累计30次", reward = "打怪爆率+10%", attr_show = {{label = "打怪爆率", value = 1000, percent = 1}}},
        {id = 142, group = "其他", name = "全服孤品", cond = "获得1件全服孤品", reward = "攻击伤害+1%", attr_show = {{label = "攻击伤害", value = 100, percent = 1}}},
        {id = 143, group = "其他", name = "改头换面", cond = "使用改名卡时，概率触发（20%）", reward = "伤害吸收+1%", attr_show = {{label = "伤害吸收", value = 100, percent = 1}}},
        {id = 144, group = "其他", name = "第一名", cond = "全服第一个注册登陆上线", reward = "打怪爆率+8%", attr_show = {{label = "打怪爆率", value = 800, percent = 1}}},
        {id = 145, group = "其他", name = "挂机佬", cond = "连续挂机10小时", reward = "对怪攻速+1%", attr_show = {{label = "对怪攻速", value = 100, percent = 1}}},
        {id = 146, group = "其他", name = "没事我溜达", cond = "在安全区移动时概率触发", reward = "移动速度+1%", attr_show = {{label = "移动速度", value = 100, percent = 1}}},
        {id = 147, group = "PVP", name = "初出江湖就挨揍", cond = "累计死亡1次", reward = "生命值+10", attr_show = {{label = "生命值", value = 10}}},
        {id = 148, group = "PVP", name = "我还能打", cond = "累计死亡10次", reward = "生命值+50", attr_show = {{label = "生命值", value = 50}}},
        {id = 149, group = "PVP", name = "打不死的小强", cond = "累计死亡50次", reward = "生命值+100", attr_show = {{label = "生命值", value = 100}}},
        {id = 150, group = "PVP", name = "死而无惧", cond = "累计死亡100次", reward = "生命值+200", attr_show = {{label = "生命值", value = 200}}},
        {id = 151, group = "PVP", name = "阴曹常客", cond = "累计死亡500次", reward = "生命值+500", attr_show = {{label = "生命值", value = 500}}},
        {id = 152, group = "PVP", name = "阎王是我熟人", cond = "累计死亡1000次", reward = "生命值+1000", attr_show = {{label = "生命值", value = 1000}}},
        {id = 153, group = "PVP", name = "刀已沾血", cond = "击杀玩家1次", reward = "攻击力+10", attr_show = {{label = "攻击", mode = "range", min = 0, max = 10}}},
        {id = 154, group = "PVP", name = "江湖恶霸", cond = "击杀玩家10次", reward = "攻击力+20", attr_show = {{label = "攻击", mode = "range", min = 0, max = 20}}},
        {id = 155, group = "PVP", name = "见谁砍谁", cond = "击杀玩家50次", reward = "攻击力+50", attr_show = {{label = "攻击", mode = "range", min = 0, max = 50}}},
        {id = 156, group = "PVP", name = "百人斩", cond = "击杀玩家100次", reward = "攻击力+100", attr_show = {{label = "攻击", mode = "range", min = 0, max = 100}}},
        {id = 157, group = "PVP", name = "红眼杀神", cond = "击杀玩家500次", reward = "攻击力+500", attr_show = {{label = "攻击", mode = "range", min = 0, max = 500}}},
        {id = 158, group = "PVP", name = "再世阎罗", cond = "击杀玩家1000次", reward = "攻击力+1000", attr_show = {{label = "攻击", mode = "range", min = 0, max = 1000}}},
        {id = 159, group = "PVP", name = "有仇当场报Lv.1", cond = "死亡后成功复仇击杀者5次", reward = "攻击力+10", attr_show = {{label = "攻击", mode = "range", min = 0, max = 10}}},
        {id = 160, group = "PVP", name = "有仇当场报Lv.2", cond = "死亡后成功复仇击杀者20次", reward = "攻击力+50", attr_show = {{label = "攻击", mode = "range", min = 0, max = 50}}},
        {id = 161, group = "PVP", name = "有仇当场报Lv.3", cond = "死亡后成功复仇击杀者50次", reward = "攻击力+100", attr_show = {{label = "攻击", mode = "range", min = 0, max = 100}}},
        {id = 162, group = "PVP", name = "专业杀手Lv.1", cond = "击杀狂暴玩家10次", reward = "PK增伤+1%", attr_show = {{label = "PK增伤", value = 100, percent = 1}}},
        {id = 163, group = "PVP", name = "专业杀手Lv.2", cond = "击杀狂暴玩家100次", reward = "PK增伤+2%", attr_show = {{label = "PK增伤", value = 200, percent = 1}}},
        {id = 164, group = "PVP", name = "专业杀手Lv.3", cond = "击杀狂暴玩家1000次", reward = "PK增伤+3%", attr_show = {{label = "PK增伤", value = 300, percent = 1}}},
        {id = 165, group = "PVP", name = "别爆了Lv.1", cond = "死亡爆装1次", reward = "死亡爆装概率-1%", attr_show = {{label = "死亡爆装概率", value = 100, percent = 1, sign = "-"}}},
        {id = 166, group = "PVP", name = "别爆了Lv.2", cond = "死亡爆装10次", reward = "死亡爆装概率-2%", attr_show = {{label = "死亡爆装概率", value = 200, percent = 1, sign = "-"}}},
        {id = 167, group = "PVP", name = "别爆了Lv.3", cond = "死亡爆装20次", reward = "死亡爆装概率-3%", attr_show = {{label = "死亡爆装概率", value = 300, percent = 1, sign = "-"}}},
        {id = 168, group = "PVP", name = "别爆了Lv.4", cond = "死亡爆装50次", reward = "死亡爆装概率-4%", attr_show = {{label = "死亡爆装概率", value = 400, percent = 1, sign = "-"}}},
        {id = 172, group = "PVP", name = "第一滴血", cond = "攻沙时，第一个击杀玩家", reward = "攻击伤害+1%", attr_show = {{label = "攻击伤害", value = 100, percent = 1}}},
        {id = 173, group = "PVP", name = "沙城杀神Lv.1", cond = "攻沙期间，击杀10名玩家", reward = "攻击+10、防御+10", attr_show = {{label = "攻击", mode = "range", min = 0, max = 10}, {label = "防御", mode = "range", min = 0, max = 10}}},
        {id = 174, group = "PVP", name = "沙城杀神Lv.2", cond = "攻沙期间，击杀50名玩家", reward = "攻击+20、防御+20", attr_show = {{label = "攻击", mode = "range", min = 0, max = 20}, {label = "防御", mode = "range", min = 0, max = 20}}},
        {id = 175, group = "PVP", name = "沙城杀神Lv.3", cond = "攻沙期间，击杀100名玩家", reward = "攻击+30、防御+30", attr_show = {{label = "攻击", mode = "range", min = 0, max = 30}, {label = "防御", mode = "range", min = 0, max = 30}}},
        {id = 176, group = "PVP", name = "皇宫魔鬼Lv.1", cond = "在皇宫内，连续击杀5名玩家，中途没死亡、回城", reward = "攻击伤害+1%", attr_show = {{label = "攻击伤害", value = 100, percent = 1}}},
        {id = 177, group = "PVP", name = "皇宫魔鬼Lv.2", cond = "在皇宫内，连续击杀10名玩家，中途没死亡、回城", reward = "攻击伤害+2%", attr_show = {{label = "攻击伤害", value = 200, percent = 1}}},
        {id = 178, group = "PVP", name = "皇宫魔鬼Lv.3", cond = "在皇宫内，连续击杀20名玩家，中途没死亡、回城", reward = "攻击伤害+3%", attr_show = {{label = "攻击伤害", value = 300, percent = 1}}},
        {id = 179, group = "PVP", name = "天下第一Lv.1", cond = "跨服武道大会活动中，击杀10名玩家", reward = "PK增伤+1%、PK减伤+1%", attr_show = {{label = "PK增伤", value = 100, percent = 1}, {label = "PK减伤", value = 100, percent = 1}}},
        {id = 180, group = "PVP", name = "天下第一Lv.2", cond = "跨服武道大会活动中，击杀50名玩家", reward = "PK增伤+1%、PK减伤+1%", attr_show = {{label = "PK增伤", value = 100, percent = 1}, {label = "PK减伤", value = 100, percent = 1}}},
        {id = 181, group = "PVP", name = "天下第一Lv.3", cond = "跨服武道大会活动中，击杀100名玩家", reward = "PK增伤+2%、PK减伤+2%", attr_show = {{label = "PK增伤", value = 200, percent = 1}, {label = "PK减伤", value = 200, percent = 1}}},
        {id = 182, group = "PVP", name = "天下第一Lv.4", cond = "跨服武道大会活动中，击杀300名玩家", reward = "PK增伤+2%、PK减伤+2%", attr_show = {{label = "PK增伤", value = 200, percent = 1}, {label = "PK减伤", value = 200, percent = 1}}},
        {id = 183, group = "PVP", name = "天下第一Lv.5", cond = "跨服武道大会活动中，击杀500名玩家", reward = "PK增伤+2%、PK减伤+2%", attr_show = {{label = "PK增伤", value = 200, percent = 1}, {label = "PK减伤", value = 200, percent = 1}}},
        {id = 184, group = "PVP", name = "关我啥事？", cond = "其他玩家攻击目标是怪物时，顺手把你杀死，概率获得", reward = "防御+10-10", attr_show = {{label = "防御", mode = "range", min = 10, max = 10}}},
        {id = 185, group = "PVP", name = "被一刀秒了", cond = "被其他玩家1刀击杀", reward = "防御+10-10", attr_show = {{label = "防御", mode = "range", min = 10, max = 10}}},
        {id = 186, group = "PVP", name = "颗秒无需报", cond = "一刀杀死其他玩家", reward = "攻击+15-15", attr_show = {{label = "攻击", mode = "range", min = 15, max = 15}}},
    },
}

cfg.attr_show_color = {
    ["攻击"] = "#ffb35c",
    ["防御"] = "#7db8ff",
    ["生命值"] = "#7ee084",
    ["固定魔法"] = "#74e3ff",
    ["攻魔道"] = "#ff8aa1",
    ["修为"] = "#68ecff",
    ["神力倍功"] = "#ffd76a",
    ["暴击伤害"] = "#ff9b6a",
    ["暴击几率"] = "#ffb86c",
    ["神圣一击概率"] = "#ff92c2",
    ["人物攻击"] = "#ffb35c",
    ["攻击伤害"] = "#ff936a",
    ["魔法伤害减少"] = "#8fd0ff",
    ["魔法伤害增加"] = "#ff9f87",
    ["对怪增伤"] = "#ffcf6e",
    ["打怪爆率"] = "#9dff8e",
    ["对怪切割"] = "#c78cff",
    ["对怪固定吸血"] = "#ff7d7d",
    ["怪物格挡"] = "#8bbdff",
    ["金币回收"] = "#ffe27a",
    ["伤害吸收"] = "#8fe0ff",
    ["PK增伤"] = "#ff8c8c",
    ["PK减伤"] = "#8cb7ff",
    ["移动速度"] = "#7dffd9",
    ["防御加成"] = "#79c7ff",
    ["对怪攻速"] = "#ffd27f",
    ["跨服怪物额外增伤"] = "#68ecff",
    ["强化不消耗道具几率"] = "#68ecff",
    ["人缘"] = "#68ecff",
    ["魅力"] = "#68ecff",
    ["受到伤害"] = "#68ecff",
    ["死亡爆装概率"] = "#ff9aa8",
}

return cfg

